---
- name: Install Docker on EC2
  hosts: all
  become: yes
  tasks:
    - name: Update the package cache
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == 'RedHat'

    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - docker
        - python3-pip

    - name: Start and enable the Docker service
      systemd:
        name: docker
        enabled: yes
        state: started
